import type {
  Product,
  Service,
  ProductCategory,
  ServiceCategory,
  Testimonial,
  GalleryImage,
  LegalDocument,
} from "./types"

export const productCategories: ProductCategory[] = [
  {
    id: "1",
    name: "Computer Products",
    slug: "computer-products",
    description: "Laptops, desktops, and computer components",
    image: "/electronics-category-modern.jpg",
  },
  {
    id: "2",
    name: "Peripherals",
    slug: "peripherals",
    description: "Keyboards, mice, monitors, and printers",
    image: "/office-equipment-modern.jpg",
  },
  {
    id: "3",
    name: "Networking",
    slug: "networking",
    description: "Routers, switches, and networking equipment",
    image: "/network-security-appliance-hardware.jpg",
  },
  {
    id: "4",
    name: "Security Cameras",
    slug: "security-cameras",
    description: "CCTV systems and surveillance solutions",
    image: "/cybersecurity-monitoring-center-modern.jpg",
  },
  {
    id: "5",
    name: "Software",
    slug: "software",
    description: "Operating systems and productivity software",
    image: "/software-development-coding-modern.jpg",
  },
  {
    id: "6",
    name: "Gaming",
    slug: "gaming",
    description: "Gaming PCs and accessories",
    image: "/electronics-category-modern.jpg",
  },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Gaming Desktop PC",
    description: "High-performance gaming computer with latest graphics card. Perfect for gaming and content creation.",
    specifications: ["Intel i7 Processor", "16GB RAM", "1TB SSD", "RTX 4060 GPU"],
    price: 85000,
    cost: 70000,
    discount: 5,
    image: "/enterprise-server-hardware-modern.jpg",
    category: "computer-products",
    isVisible: true,
    showPrice: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "CCTV Security System",
    description: "Complete surveillance system with high-definition cameras and remote monitoring capabilities.",
    specifications: ["4 HD Cameras", "DVR with 1TB Storage", "Mobile App Access", "Night Vision"],
    price: 25000,
    cost: 18000,
    image: "/cybersecurity-monitoring-center-modern.jpg",
    category: "security-cameras",
    isVisible: true,
    showPrice: true,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "3",
    name: "Wireless Router Pro",
    description: "High-speed wireless router with advanced security features and extended range coverage.",
    specifications: ["WiFi 6", "Dual Band", "4 Gigabit Ports", "Advanced Security"],
    price: 8500,
    image: "/network-security-appliance-hardware.jpg",
    category: "networking",
    isVisible: true,
    showPrice: true,
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "4",
    name: "Network Security Appliance",
    description: "Enterprise-grade firewall and intrusion detection system with AI-powered threat analysis.",
    specifications: ["10Gbps Throughput", "Zero Trust Architecture", "ML Threat Detection", "24/7 Monitoring"],
    price: 4599,
    discount: 15,
    image: "/network-security-appliance-hardware.jpg",
    category: "computer-products",
    isVisible: true,
    showPrice: true,
    createdAt: new Date("2024-03-25"),
  },
  {
    id: "5",
    name: "Business Laptop",
    description: "Professional laptop perfect for business use with long battery life and robust security features.",
    specifications: ["Intel i5 Processor", "8GB RAM", "512GB SSD", "14-inch Display"],
    price: 55000,
    image: "/office-equipment-modern.jpg",
    category: "computer-products",
    isVisible: true,
    showPrice: true,
    createdAt: new Date("2024-04-05"),
  },
  {
    id: "6",
    name: "Ergonomic Workstation",
    description: "Height-adjustable desk with integrated cable management and wellness features.",
    specifications: ["Electric Lift", "Memory Presets", "USB-C Hub", "Anti-Fatigue Mat"],
    price: 1899,
    discount: 5,
    image: "/ergonomic-workstation-desk-modern.jpg",
    category: "office",
    isVisible: true,
    showPrice: true,
    createdAt: new Date("2024-04-18"),
  },
]

export const serviceCategories: ServiceCategory[] = [
  {
    id: "1",
    name: "Consulting",
    slug: "consulting",
    description: "Strategic business and technology consulting",
  },
  {
    id: "2",
    name: "Implementation",
    slug: "implementation",
    description: "System setup, deployment, and integration services",
  },
  {
    id: "3",
    name: "Support",
    slug: "support",
    description: "Ongoing maintenance and technical support",
  },
]

export const services: Service[] = [
  {
    id: "1",
    name: "AI Strategy Consulting",
    description:
      "Comprehensive AI adoption strategy tailored to your business needs. We analyze your operations and identify opportunities for AI integration.",
    image: "/ai-consulting-business-meeting-modern.jpg",
    category: "consulting",
    tags: ["AI-Powered", "Strategic", "Enterprise"],
    isVisible: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "2",
    name: "Cloud Infrastructure Setup",
    description:
      "End-to-end cloud infrastructure deployment on AWS, Azure, or GCP. Includes security hardening and cost optimization.",
    image: "/cloud-infrastructure-data-center-modern.jpg",
    category: "implementation",
    tags: ["Cloud", "DevOps", "Security"],
    isVisible: true,
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "3",
    name: "24/7 Technical Support",
    description:
      "Round-the-clock technical support with guaranteed response times. Dedicated account manager and priority escalation.",
    image: "/technical-support-team-office-modern.jpg",
    category: "support",
    tags: ["24/7", "Premium", "Dedicated"],
    isVisible: true,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "4",
    name: "Digital Transformation",
    description:
      "Complete digital transformation journey from assessment to implementation. Modernize your legacy systems and processes.",
    image: "/digital-transformation-technology-modern.jpg",
    category: "consulting",
    tags: ["Transformation", "Modernization", "Advanced"],
    isVisible: true,
    createdAt: new Date("2024-03-15"),
  },
  {
    id: "5",
    name: "Custom Software Development",
    description:
      "Bespoke software solutions built to your exact specifications. Agile development with continuous delivery.",
    image: "/software-development-coding-modern.jpg",
    category: "implementation",
    tags: ["Custom", "Agile", "Full-Stack"],
    isVisible: true,
    createdAt: new Date("2024-04-01"),
  },
  {
    id: "6",
    name: "Managed Security Services",
    description:
      "Comprehensive security monitoring, threat detection, and incident response. Protect your digital assets 24/7.",
    image: "/cybersecurity-monitoring-center-modern.jpg",
    category: "support",
    tags: ["Security", "Managed", "Compliance"],
    isVisible: true,
    createdAt: new Date("2024-04-20"),
  },
]

export const testimonials: Testimonial[] = [
  {
    id: "1",
    quote:
      "Yog Computers installed our entire CCTV system perfectly. The mobile app monitoring works great and gives us peace of mind. Highly recommended!",
    author: "Rajesh Sharma",
    role: "Owner",
    company: "Sharma Electronics Store",
    logo: "/placeholder.svg?height=60&width=120",
    rating: 5,
    isVerified: true,
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "2",
    quote: "My laptop was completely dead, but Yog Computers brought it back to life! Fast service, fair pricing, and very knowledgeable technicians.",
    author: "Priya Patel",
    role: "Student",
    company: "Bharti Vidyapeeth University",
    logo: "/placeholder.svg?height=60&width=120",
    rating: 5,
    isVerified: true,
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "3",
    quote: "Excellent electrical work! They rewired our entire office safely and efficiently. Professional team with transparent pricing. Will definitely call again.",
    author: "Amit Joshi",
    role: "Manager",
    company: "Joshi Trading Company",
    rating: 5,
    isVerified: true,
    createdAt: new Date("2024-04-10"),
  },
]

export const galleryImages: GalleryImage[] = [
  {
    id: "1",
    title: "Annual Conference 2024",
    url: "/placeholder.svg?height=600&width=800",
    category: "events",
    createdAt: new Date(),
  },
  {
    id: "2",
    title: "Product Launch",
    url: "/placeholder.svg?height=600&width=800",
    category: "events",
    createdAt: new Date(),
  },
  {
    id: "3",
    title: "Server Room",
    url: "/placeholder.svg?height=600&width=800",
    category: "products",
    createdAt: new Date(),
  },
  {
    id: "4",
    title: "Automation Demo",
    url: "/placeholder.svg?height=600&width=800",
    category: "products",
    createdAt: new Date(),
  },
  {
    id: "5",
    title: "Team Workshop",
    url: "/placeholder.svg?height=600&width=800",
    category: "services",
    createdAt: new Date(),
  },
  {
    id: "6",
    title: "Client Meeting",
    url: "/placeholder.svg?height=600&width=800",
    category: "services",
    createdAt: new Date(),
  },
  {
    id: "7",
    title: "Headquarters",
    url: "/placeholder.svg?height=600&width=800",
    category: "office",
    createdAt: new Date(),
  },
  {
    id: "8",
    title: "Open Office",
    url: "/placeholder.svg?height=600&width=800",
    category: "office",
    createdAt: new Date(),
  },
]

export const legalDocuments: LegalDocument[] = [
  {
    id: "1",
    name: "GST Registration Certificate",
    description: "Official GST registration documentation",
    fileUrl: "#",
    fileType: "pdf",
    category: "gst",
    createdAt: new Date(),
  },
  {
    id: "2",
    name: "Certificate of Incorporation",
    description: "Company incorporation documents",
    fileUrl: "#",
    fileType: "pdf",
    category: "ownership",
    createdAt: new Date(),
  },
  {
    id: "3",
    name: "Service Level Agreement",
    description: "Standard SLA for all service contracts",
    fileUrl: "#",
    fileType: "pdf",
    category: "service",
    createdAt: new Date(),
  },
  {
    id: "4",
    name: "Product Warranty Terms",
    description: "Warranty terms and conditions for products",
    fileUrl: "#",
    fileType: "pdf",
    category: "product",
    createdAt: new Date(),
  },
]
