import type { Product, Category } from './types'

// Sample products data for fallback
export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "AI Analytics Platform",
    slug: "ai-analytics-platform",
    description: "Advanced AI-powered analytics platform for enterprise data insights with real-time processing and machine learning capabilities. Transform your data into actionable insights with our comprehensive suite of analytics tools.",
    shortDescription: "AI-powered analytics for enterprises",
    price: 299,
    discount: 20,
    showPrice: true,
    image: "/ai-consulting-business-meeting-modern.jpg",
    isFeatured: true,
    isActive: true,
    status: "PUBLISHED" as any,
    stockStatus: "IN_STOCK" as any,
    category: { id: "1", name: "Software", slug: "software" } as any,
    specifications: [
      "Real-time data processing engine",
      "Advanced machine learning models",
      "Cloud-native deployment ready",
      "RESTful API integration",
      "Interactive dashboard builder",
      "Automated report generation"
    ],
    features: ["AI-Powered", "Cloud-Native", "Real-time Analytics"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-12-15")
  },
  {
    id: "2", 
    name: "Cloud Infrastructure Suite",
    slug: "cloud-infrastructure-suite",
    description: "Complete cloud infrastructure management platform with automated scaling, monitoring, and security features built for modern enterprises. Manage your entire cloud ecosystem from a single dashboard.",
    shortDescription: "Enterprise cloud management platform",
    price: 199,
    discount: 0,
    showPrice: true,
    image: "/cloud-infrastructure-data-center-modern.jpg",
    isFeatured: true,
    isActive: true,
    status: "PUBLISHED" as any,
    stockStatus: "IN_STOCK" as any,
    category: { id: "2", name: "Cloud", slug: "cloud" } as any,
    specifications: [
      "Auto-scaling infrastructure",
      "24/7 monitoring and alerting",
      "Enterprise-grade security",
      "Multi-region deployment",
      "Cost optimization tools",
      "Disaster recovery planning"
    ],
    features: ["Cloud-Native", "Auto-scaling", "Enterprise Security"],
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-12-10")
  },
  {
    id: "3",
    name: "Cybersecurity Shield Pro",
    slug: "cybersecurity-shield-pro",
    description: "Advanced cybersecurity platform providing comprehensive threat protection, real-time monitoring, and automated incident response for enterprises. Protect your digital assets with military-grade security.",
    shortDescription: "Enterprise cybersecurity protection",
    price: 399,
    discount: 15,
    showPrice: true,
    image: "/cybersecurity-monitoring-center-modern.jpg",
    isFeatured: true,
    isActive: true,
    status: "PUBLISHED" as any,
    stockStatus: "IN_STOCK" as any,
    category: { id: "3", name: "Security", slug: "security" } as any,
    specifications: [
      "Advanced threat detection",
      "Real-time security monitoring",
      "Automated incident response",
      "Compliance reporting suite",
      "Vulnerability assessment tools",
      "Security analytics dashboard"
    ],
    features: ["Advanced Security", "Real-time Monitoring", "Automated Response"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-12-05")
  },
  {
    id: "4",
    name: "Digital Transformation Suite",
    slug: "digital-transformation-suite",
    description: "Complete digital transformation platform helping businesses modernize operations, automate workflows, and enhance customer experiences. Drive innovation across your entire organization.",
    shortDescription: "Complete digital transformation platform",
    price: 499,
    discount: 0,
    showPrice: false,
    image: "/digital-transformation-technology-modern.jpg",
    isFeatured: false,
    isActive: true,
    status: "PUBLISHED" as any,
    stockStatus: "IN_STOCK" as any,
    category: { id: "4", name: "Digital Services", slug: "digital-services" } as any,
    specifications: [
      "Workflow automation engine",
      "Customer experience optimization",
      "Enterprise data integration",
      "Process optimization tools",
      "Change management support",
      "ROI tracking and analytics"
    ],
    features: ["Workflow Automation", "CX Enhancement", "Data Integration"],
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-11-20")
  },
  {
    id: "5",
    name: "Enterprise Automation Platform",
    slug: "enterprise-automation-platform",
    description: "Comprehensive automation platform that streamlines business processes, reduces manual work, and increases operational efficiency across departments. Automate repetitive tasks and focus on strategic initiatives.",
    shortDescription: "Complete business process automation",
    price: 349,
    discount: 10,
    showPrice: true,
    image: "/industrial-automation-kit-modern.jpg",
    isFeatured: true,
    isActive: true,
    status: "PUBLISHED" as any,
    stockStatus: "IN_STOCK" as any,
    category: { id: "5", name: "Automation", slug: "automation" } as any,
    specifications: [
      "Intelligent process automation",
      "Workflow management system",
      "API integration platform",
      "Analytics and reporting dashboard",
      "Audit trail and compliance",
      "Multi-department coordination"
    ],
    features: ["Workflow Automation", "API Integration", "Real-time Analytics"],
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-12-01")
  },
  {
    id: "6",
    name: "Smart Office Hub",
    slug: "smart-office-hub",
    description: "Intelligent office management system that connects and controls all your office devices, optimizes energy usage, and enhances workplace productivity. Create a smarter, more efficient workplace.",
    shortDescription: "Intelligent office management system",
    price: 159,
    discount: 0,
    showPrice: true,
    image: "/smart-office-hub-device-modern.jpg",
    isFeatured: false,
    isActive: true,
    status: "PUBLISHED" as any,
    stockStatus: "IN_STOCK" as any,
    category: { id: "6", name: "IoT", slug: "iot" } as any,
    specifications: [
      "Universal device connectivity",
      "Energy optimization algorithms",
      "Mobile app control interface",
      "Voice assistant integration",
      "Environmental monitoring",
      "Automated scheduling system"
    ],
    features: ["IoT Integration", "Energy Optimization", "Mobile Control"],
    createdAt: new Date("2024-04-12"),
    updatedAt: new Date("2024-11-15")
  },
  {
    id: "7",
    name: "Network Security Appliance",
    slug: "network-security-appliance",
    description: "Enterprise-grade network security hardware solution providing comprehensive protection against advanced cyber threats and unauthorized access. Secure your network perimeter with confidence.",
    shortDescription: "Enterprise network security hardware",
    price: 899,
    discount: 5,
    showPrice: true,
    image: "/network-security-appliance-hardware.jpg",
    isFeatured: true,
    isActive: true,
    status: "PUBLISHED" as any,
    stockStatus: "IN_STOCK" as any,
    category: { id: "3", name: "Security", slug: "security" } as any,
    specifications: [
      "Hardware firewall protection",
      "Intrusion detection system",
      "VPN gateway support",
      "High availability clustering",
      "Traffic analysis engine",
      "Centralized management console"
    ],
    features: ["Hardware Security", "High Performance", "Enterprise Grade"],
    createdAt: new Date("2024-01-30"),
    updatedAt: new Date("2024-12-08")
  },
  {
    id: "8",
    name: "Professional Development Suite",
    slug: "professional-development-suite",
    description: "Comprehensive software development platform with integrated tools for coding, testing, deployment, and team collaboration. Accelerate your development lifecycle with professional-grade tools.",
    shortDescription: "Complete development platform",
    price: 249,
    discount: 0,
    showPrice: true,
    image: "/software-development-coding-modern.jpg",
    isFeatured: false,
    isActive: true,
    status: "PUBLISHED" as any,
    stockStatus: "IN_STOCK" as any,
    category: { id: "1", name: "Software", slug: "software" } as any,
    specifications: [
      "Integrated development environment",
      "Continuous integration pipeline",
      "Team collaboration tools",
      "Version control system",
      "Automated testing framework",
      "Deployment automation"
    ],
    features: ["Development Tools", "Team Collaboration", "CI/CD Pipeline"],
    createdAt: new Date("2024-03-18"),
    updatedAt: new Date("2024-11-25")
  },
  {
    id: "9",
    name: "Enterprise Server Hardware",
    slug: "enterprise-server-hardware",
    description: "High-performance enterprise server hardware optimized for demanding workloads with redundant systems and enterprise support. Built for mission-critical applications and maximum uptime.",
    shortDescription: "High-performance enterprise servers",
    price: 2499,
    discount: 8,
    showPrice: false,
    image: "/enterprise-server-hardware-modern.jpg",
    isFeatured: true,
    isActive: true,
    status: "PUBLISHED" as any,
    stockStatus: "IN_STOCK" as any,
    category: { id: "7", name: "Hardware", slug: "hardware" } as any,
    specifications: [
      "Redundant power supply systems",
      "Hot-swappable drive bays",
      "Remote management interface",
      "Enterprise warranty coverage",
      "Scalable memory architecture",
      "High-speed network connectivity"
    ],
    features: ["Enterprise Grade", "High Availability", "Remote Management"],
    createdAt: new Date("2024-02-14"),
    updatedAt: new Date("2024-12-12")
  },
  {
    id: "10",
    name: "Technical Support Services",
    slug: "technical-support-services",
    description: "Comprehensive technical support services providing expert assistance, troubleshooting, and maintenance for all your technology needs. Get the support you need, when you need it.",
    shortDescription: "Expert technical support services",
    price: 199,
    discount: 0,
    showPrice: true,
    image: "/technical-support-team-office-modern.jpg",
    isFeatured: false,
    isActive: true,
    status: "PUBLISHED" as any,
    stockStatus: "IN_STOCK" as any,
    category: { id: "8", name: "Support", slug: "support" } as any,
    specifications: [
      "24/7 technical availability",
      "Certified expert technicians",
      "Remote assistance capabilities",
      "On-site support options",
      "Escalation management",
      "Knowledge base access"
    ],
    features: ["24/7 Support", "Expert Team", "Remote & On-site"],
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-11-30")
  }
]

export const sampleCategories: Category[] = [
  { 
    id: "1", 
    name: "Software", 
    slug: "software", 
    description: "Enterprise software solutions for modern businesses",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01")
  },
  { 
    id: "2", 
    name: "Cloud", 
    slug: "cloud", 
    description: "Cloud infrastructure and platform services",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01")
  },
  { 
    id: "3", 
    name: "Security", 
    slug: "security", 
    description: "Comprehensive cybersecurity solutions",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01")
  },
  { 
    id: "4", 
    name: "Digital Services", 
    slug: "digital-services", 
    description: "Digital transformation and consulting services",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01")
  },
  { 
    id: "5", 
    name: "Automation", 
    slug: "automation", 
    description: "Business process automation solutions",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01")
  },
  { 
    id: "6", 
    name: "IoT", 
    slug: "iot", 
    description: "Internet of Things and smart device solutions",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01")
  },
  { 
    id: "7", 
    name: "Hardware", 
    slug: "hardware", 
    description: "Enterprise hardware and infrastructure",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01")
  },
  { 
    id: "8", 
    name: "Support", 
    slug: "support", 
    description: "Technical support and maintenance services",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01")
  }
]